### PR TITLE
Fix mission indices

### LINKED ISSUE #1031: mavlink_mission_item_to_mission_item_indices never cleared
_mission_data.mavlink_mission_item_to_mission_item_indices is never cleared which means we might have more mavlink_mission_item_to_mission_item_indices than we want if we download a list of items smaller than the previous one

https://github.com/mavlink/MAVSDK/blob/8afd4640cebf4fae242a9ff9650d354cebab2f48/src/plugins/mission/mission_impl.cpp#L241

### PR DESCRIPTION
**Pull request by julianoes**
This is the follow up to @roangel's PR #1105.

Also fixes #1031.

### CODE REVIEW

File: src/plugins/mission/mission_impl.cpp [hunk 1]
```diff
@@ -477,10 +473,10 @@ MissionImpl::convert_to_int_items(const std::vector<MissionItem>& mission_items)
                                                   0,
                                                   MAV_MISSION_TYPE_MISSION};
 
-        _mission_data.mavlink_mission_item_to_mission_item_indices.insert(
-            std::pair<int, int>{static_cast<int>(int_items.size()), item_i});
+        _mission_data.mavlink_mission_item_to_mission_item_indices.push_back(item_i);
         int_items.push_back(next_item);
     }
+
```
Comment (roangel) [inline src/plugins/mission/mission_impl.cpp:479]:
```suggestion
```

**Comment by julianoes** [comment]
The error is another one of #882.
